import StoreProvider from './StoreProvider';
import './globals.css';

// const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// };

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<StoreProvider>
			<html lang="en">
				<body className="bg-gradient min-h-screen">
					<div className="container">
						{children}
					</div>
				</body>
			</html>
		</StoreProvider>
	);
}
